name: macOS Build

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        os: [macos-14]
        qt-version: ['6.8']
        qt-target: ['desktop']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Setup environment
      run: |
        sed -i -e '/^#/d' .github/config.env
        sed -i -e '/^$/d' .github/config.env
        cat .github/config.env >> "${GITHUB_ENV}"
      shell: bash
    - name: Set up node.js
      uses: actions/setup-node@v3
    # Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        host: 'mac'
        target: ${{ matrix.qt-target }}
        modules: ''
    # Build
    - name: Build
      run: .ci/macos_build.sh
      shell: bash
    # Upload
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-Qt-${{ matrix.qt-version }}
        path: '*.dmg'
