name: Unit tests

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nlohmann-json3-dev libutfcpp-dev xvfb libxcb-cursor0
      shell: bash
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.*'
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSCRATCHCPP_PLAYER_BUILD_UNIT_TESTS=ON

    - name: Build
      run: xvfb-run cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j$(nproc --all)

    - name: Run unit tests
      run: xvfb-run ctest --test-dir build -V
